import sys, os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from UcsBase import ManagedObject
sys.path.remove(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

class ApeParam(ManagedObject):
	def __init__(self):
		ManagedObject.__init__(self,"ApeParam")

	@staticmethod
	def ClassId():
		return "apeParam"

	DN = "Dn"
	KEY = "Key"
	RN = "Rn"
	STATUS = "Status"
	VALUE = "Value"

	CONST_KEY_ACTIVE_IMAGE = "ACTIVE_IMAGE"
	CONST_KEY_BIOS_ACTIVE_IMAGE = "BIOS_ACTIVE_IMAGE"
	CONST_KEY_BIOS_ALTERNATE_IMAGE = "BIOS_ALTERNATE_IMAGE"
	CONST_KEY_BIOS_STARTUP_IMAGE = "BIOS_STARTUP_IMAGE"
	CONST_KEY_BLADE_POWER_BUDGET = "BLADE_POWER_BUDGET"
	CONST_KEY_BOOT_INSTANCE_ID = "BOOT_INSTANCE_ID"
	CONST_KEY_CHASSIS_POWER_BUDGET = "CHASSIS_POWER_BUDGET"
	CONST_KEY_CMC_MODEL = "CMC_MODEL"
	CONST_KEY_COMM_STATUS = "COMM_STATUS"
	CONST_KEY_HEALTH_STATUS = "HEALTH_STATUS"
	CONST_KEY_IMAGE1_STATUS = "IMAGE1_STATUS"
	CONST_KEY_IMAGE2_STATUS = "IMAGE2_STATUS"
	CONST_KEY_LOCATE_LED_STATE = "LOCATE_LED_STATE"
	CONST_KEY_MEZZ_POST = "MEZZ_POST"
	CONST_KEY_PECI_TCONTROL = "PECI_TCONTROL"
	CONST_KEY_PEER_POST_STATUS = "PEER_POST_STATUS"
	CONST_KEY_PLD_UPDATE_STATUS = "PLD_UPDATE_STATUS"
	CONST_KEY_PLD_VER = "PLD_VER"
	CONST_KEY_POST_STATUS = "POST_STATUS"
	CONST_KEY_POWER_POLICY = "POWER_POLICY"
	CONST_KEY_POWER_POLICY_PEER = "POWER_POLICY_PEER"
	CONST_KEY_POWER_STATUS = "POWER_STATUS"
	CONST_KEY_RUNNING_IMAGE = "RUNNING_IMAGE"
	CONST_KEY_SEL_CNTRS = "SEL_CNTRS"
	CONST_KEY_SW_BOOT_ORDER = "SW_BOOT_ORDER"
	CONST_KEY_SW_UPDATE_STATUS = "SW_UPDATE_STATUS"
	CONST_KEY_SW_VER_IMAGE_1 = "SW_VER_IMAGE_1"
	CONST_KEY_SW_VER_IMAGE_2 = "SW_VER_IMAGE_2"
	CONST_KEY_THERMAL_INFO = "THERMAL_INFO"
	CONST_KEY_UBOOT_VERSION = "UBOOT_VERSION"
	CONST_KEY_UNKNOWN = "UNKNOWN"
