import sys, os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from UcsBase import ManagedObject
sys.path.remove(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

class BiosVfPCISlotOptionROMEnable(ManagedObject):
	def __init__(self):
		ManagedObject.__init__(self,"BiosVfPCISlotOptionROMEnable")

	@staticmethod
	def ClassId():
		return "biosVfPCISlotOptionROMEnable"

	DN = "Dn"
	RN = "Rn"
	STATUS = "Status"
	VP_PCIE_SLOT_SASOPTION_ROM = "VpPCIeSlotSASOptionROM"
	VP_SLOT10_STATE = "VpSlot10State"
	VP_SLOT1_STATE = "VpSlot1State"
	VP_SLOT2_STATE = "VpSlot2State"
	VP_SLOT3_STATE = "VpSlot3State"
	VP_SLOT4_STATE = "VpSlot4State"
	VP_SLOT5_STATE = "VpSlot5State"
	VP_SLOT6_STATE = "VpSlot6State"
	VP_SLOT7_STATE = "VpSlot7State"
	VP_SLOT8_STATE = "VpSlot8State"
	VP_SLOT9_STATE = "VpSlot9State"
	VP_SLOT_MEZZ_STATE = "VpSlotMezzState"

	CONST_VP_PCIE_SLOT_SASOPTION_ROM_DISABLED = "disabled"
	CONST_VP_PCIE_SLOT_SASOPTION_ROM_ENABLED = "enabled"
	CONST_VP_PCIE_SLOT_SASOPTION_ROM_LEGACY_ONLY = "legacy-only"
	CONST_VP_PCIE_SLOT_SASOPTION_ROM_PLATFORM_DEFAULT = "platform-default"
	CONST_VP_PCIE_SLOT_SASOPTION_ROM_PLATFORM_RECOMMENDED = "platform-recommended"
	CONST_VP_PCIE_SLOT_SASOPTION_ROM_UEFI_ONLY = "uefi-only"
	CONST_VP_SLOT10_STATE_DISABLED = "disabled"
	CONST_VP_SLOT10_STATE_ENABLED = "enabled"
	CONST_VP_SLOT10_STATE_LEGACY_ONLY = "legacy-only"
	CONST_VP_SLOT10_STATE_PLATFORM_DEFAULT = "platform-default"
	CONST_VP_SLOT10_STATE_PLATFORM_RECOMMENDED = "platform-recommended"
	CONST_VP_SLOT10_STATE_UEFI_ONLY = "uefi-only"
	CONST_VP_SLOT1_STATE_DISABLED = "disabled"
	CONST_VP_SLOT1_STATE_ENABLED = "enabled"
	CONST_VP_SLOT1_STATE_PLATFORM_DEFAULT = "platform-default"
	CONST_VP_SLOT1_STATE_PLATFORM_RECOMMENDED = "platform-recommended"
	CONST_VP_SLOT2_STATE_DISABLED = "disabled"
	CONST_VP_SLOT2_STATE_ENABLED = "enabled"
	CONST_VP_SLOT2_STATE_PLATFORM_DEFAULT = "platform-default"
	CONST_VP_SLOT2_STATE_PLATFORM_RECOMMENDED = "platform-recommended"
	CONST_VP_SLOT3_STATE_DISABLED = "disabled"
	CONST_VP_SLOT3_STATE_ENABLED = "enabled"
	CONST_VP_SLOT3_STATE_PLATFORM_DEFAULT = "platform-default"
	CONST_VP_SLOT3_STATE_PLATFORM_RECOMMENDED = "platform-recommended"
	CONST_VP_SLOT4_STATE_DISABLED = "disabled"
	CONST_VP_SLOT4_STATE_ENABLED = "enabled"
	CONST_VP_SLOT4_STATE_PLATFORM_DEFAULT = "platform-default"
	CONST_VP_SLOT4_STATE_PLATFORM_RECOMMENDED = "platform-recommended"
	CONST_VP_SLOT5_STATE_DISABLED = "disabled"
	CONST_VP_SLOT5_STATE_ENABLED = "enabled"
	CONST_VP_SLOT5_STATE_PLATFORM_DEFAULT = "platform-default"
	CONST_VP_SLOT5_STATE_PLATFORM_RECOMMENDED = "platform-recommended"
	CONST_VP_SLOT6_STATE_DISABLED = "disabled"
	CONST_VP_SLOT6_STATE_ENABLED = "enabled"
	CONST_VP_SLOT6_STATE_PLATFORM_DEFAULT = "platform-default"
	CONST_VP_SLOT6_STATE_PLATFORM_RECOMMENDED = "platform-recommended"
	CONST_VP_SLOT7_STATE_DISABLED = "disabled"
	CONST_VP_SLOT7_STATE_ENABLED = "enabled"
	CONST_VP_SLOT7_STATE_PLATFORM_DEFAULT = "platform-default"
	CONST_VP_SLOT7_STATE_PLATFORM_RECOMMENDED = "platform-recommended"
	CONST_VP_SLOT8_STATE_DISABLED = "disabled"
	CONST_VP_SLOT8_STATE_ENABLED = "enabled"
	CONST_VP_SLOT8_STATE_LEGACY_ONLY = "legacy-only"
	CONST_VP_SLOT8_STATE_PLATFORM_DEFAULT = "platform-default"
	CONST_VP_SLOT8_STATE_PLATFORM_RECOMMENDED = "platform-recommended"
	CONST_VP_SLOT8_STATE_UEFI_ONLY = "uefi-only"
	CONST_VP_SLOT9_STATE_DISABLED = "disabled"
	CONST_VP_SLOT9_STATE_ENABLED = "enabled"
	CONST_VP_SLOT9_STATE_LEGACY_ONLY = "legacy-only"
	CONST_VP_SLOT9_STATE_PLATFORM_DEFAULT = "platform-default"
	CONST_VP_SLOT9_STATE_PLATFORM_RECOMMENDED = "platform-recommended"
	CONST_VP_SLOT9_STATE_UEFI_ONLY = "uefi-only"
	CONST_VP_SLOT_MEZZ_STATE_DISABLED = "disabled"
	CONST_VP_SLOT_MEZZ_STATE_ENABLED = "enabled"
	CONST_VP_SLOT_MEZZ_STATE_PLATFORM_DEFAULT = "platform-default"
	CONST_VP_SLOT_MEZZ_STATE_PLATFORM_RECOMMENDED = "platform-recommended"
