import sys, os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from UcsBase import ManagedObject
sys.path.remove(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

class DcxVIf(ManagedObject):
	def __init__(self):
		ManagedObject.__init__(self,"DcxVIf")

	@staticmethod
	def ClassId():
		return "dcxVIf"

	ADMIN_STATE = "AdminState"
	COOKIE = "Cookie"
	DN = "Dn"
	EP_DN = "EpDn"
	ID = "Id"
	IF_ROLE = "IfRole"
	IF_TYPE = "IfType"
	INST_TYPE = "InstType"
	LC = "Lc"
	LINK_STATE = "LinkState"
	LOCALE = "Locale"
	NAME = "Name"
	OPER_STATE = "OperState"
	PEER_DN = "PeerDn"
	PROT_PEER_ID = "ProtPeerId"
	PROT_ROLE = "ProtRole"
	PROT_STATE = "ProtState"
	QOS_CONTROL = "QosControl"
	RN = "Rn"
	STATE = "State"
	STATUS = "Status"
	SWITCH_ID = "SwitchId"
	TAG = "Tag"
	TRANSPORT = "Transport"
	TYPE = "Type"

	CONST_ADMIN_STATE_DISABLED = "disabled"
	CONST_ADMIN_STATE_ENABLED = "enabled"
	CONST_IF_ROLE_DIAG = "diag"
	CONST_IF_ROLE_FCOE_NAS_STORAGE = "fcoe-nas-storage"
	CONST_IF_ROLE_FCOE_STORAGE = "fcoe-storage"
	CONST_IF_ROLE_FCOE_UPLINK = "fcoe-uplink"
	CONST_IF_ROLE_MGMT = "mgmt"
	CONST_IF_ROLE_MONITOR = "monitor"
	CONST_IF_ROLE_NAS_STORAGE = "nas-storage"
	CONST_IF_ROLE_NETWORK = "network"
	CONST_IF_ROLE_NETWORK_FCOE_UPLINK = "network-fcoe-uplink"
	CONST_IF_ROLE_SERVER = "server"
	CONST_IF_ROLE_SERVICE = "service"
	CONST_IF_ROLE_STORAGE = "storage"
	CONST_IF_ROLE_UNKNOWN = "unknown"
	CONST_IF_TYPE_AGGREGATION = "aggregation"
	CONST_IF_TYPE_PHYSICAL = "physical"
	CONST_IF_TYPE_UNKNOWN = "unknown"
	CONST_IF_TYPE_VIRTUAL = "virtual"
	CONST_INST_TYPE_DEFAULT = "default"
	CONST_INST_TYPE_DYNAMIC = "dynamic"
	CONST_INST_TYPE_DYNAMIC_VF = "dynamic-vf"
	CONST_INST_TYPE_MANUAL = "manual"
	CONST_LC_ALLOCATED = "allocated"
	CONST_LC_AVAILABLE = "available"
	CONST_LC_DEALLOCATED = "deallocated"
	CONST_LC_REPURPOSED = "repurposed"
	CONST_LINK_STATE_ADMIN_DOWN = "admin-down"
	CONST_LINK_STATE_DOWN = "down"
	CONST_LINK_STATE_ERROR = "error"
	CONST_LINK_STATE_UNALLOCATED = "unallocated"
	CONST_LINK_STATE_UNAVAILABLE = "unavailable"
	CONST_LINK_STATE_UNKNOWN = "unknown"
	CONST_LINK_STATE_UP = "up"
	CONST_OPER_STATE_ACTIVE = "active"
	CONST_OPER_STATE_ADMIN_DOWN = "admin-down"
	CONST_OPER_STATE_ERROR = "error"
	CONST_OPER_STATE_LINK_DOWN = "link-down"
	CONST_OPER_STATE_PASSIVE = "passive"
	CONST_OPER_STATE_UNKNOWN = "unknown"
	CONST_PROT_ROLE_BACKUP = "backup"
	CONST_PROT_ROLE_PRIMARY = "primary"
	CONST_PROT_ROLE_UNPROTECTED = "unprotected"
	CONST_PROT_STATE_ACTIVE = "active"
	CONST_PROT_STATE_NO_PROTECTION = "no-protection"
	CONST_PROT_STATE_PASSIVE = "passive"
	CONST_QOS_CONTROL_FULL = "full"
	CONST_QOS_CONTROL_FULL_WITH_EXCEPTION = "full-with-exception"
	CONST_QOS_CONTROL_NONE = "none"
	CONST_STATE_CREATE_PEND = "CreatePend"
	CONST_STATE_CREATING = "Creating"
	CONST_STATE_DESTROY_PEND = "DestroyPend"
	CONST_STATE_DESTROYING = "Destroying"
	CONST_STATE_MODIFY_PEND = "ModifyPend"
	CONST_STATE_MODIFYING = "Modifying"
	CONST_STATE_PRESENT = "Present"
	CONST_STATE_UNKNOWN = "Unknown"
	CONST_SWITCH_ID_A = "A"
	CONST_SWITCH_ID_B = "B"
	CONST_SWITCH_ID_NONE = "NONE"
