import sys, os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from UcsBase import ManagedObject
sys.path.remove(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

class EtherSwitchIntFIo(ManagedObject):
	def __init__(self):
		ManagedObject.__init__(self,"EtherSwitchIntFIo")

	@staticmethod
	def ClassId():
		return "etherSwitchIntFIo"

	ACK = "Ack"
	ADMIN_STATE = "AdminState"
	CHASSIS_ID = "ChassisId"
	DEL_FE_TS = "DelFeTs"
	DISCOVERY = "Discovery"
	DN = "Dn"
	ENCAP = "Encap"
	EP_DN = "EpDn"
	IF_ROLE = "IfRole"
	IF_TYPE = "IfType"
	LOCALE = "Locale"
	MODE = "Mode"
	MODEL = "Model"
	NAME = "Name"
	NEW_FE_TS = "NewFeTs"
	OPER_STATE = "OperState"
	PEER_CHASSIS_ID = "PeerChassisId"
	PEER_DN = "PeerDn"
	PEER_PORT_ID = "PeerPortId"
	PEER_SLOT_ID = "PeerSlotId"
	PORT_ID = "PortId"
	REVISION = "Revision"
	RN = "Rn"
	SERIAL = "Serial"
	SLOT_ID = "SlotId"
	STATE_QUAL = "StateQual"
	STATUS = "Status"
	SWITCH_ID = "SwitchId"
	TRANSPORT = "Transport"
	TS = "Ts"
	TYPE = "Type"
	VENDOR = "Vendor"
	XCVR_TYPE = "XcvrType"

	CONST_ACK_ACK_IN_PROGRESS = "ack-in-progress"
	CONST_ACK_ACKNOWLEDGED = "acknowledged"
	CONST_ACK_AUTO_ACK = "auto-ack"
	CONST_ACK_EVALUATION = "evaluation"
	CONST_ACK_OK = "ok"
	CONST_ACK_REMOVING = "removing"
	CONST_ACK_UN_ACKNOWLEDGED = "un-acknowledged"
	CONST_ACK_UN_INITIALIZED = "un-initialized"
	CONST_ACK_UNSUPPORTED_CONNECTIVITY = "unsupported-connectivity"
	CONST_ADMIN_STATE_DISABLED = "disabled"
	CONST_ADMIN_STATE_ENABLED = "enabled"
	CONST_CHASSIS_ID_N_A = "N/A"
	CONST_DEL_FE_TS_NEVER = "never"
	CONST_DISCOVERY_ABSENT = "absent"
	CONST_DISCOVERY_MIS_CONNECT = "mis-connect"
	CONST_DISCOVERY_MISSING = "missing"
	CONST_DISCOVERY_NEW = "new"
	CONST_DISCOVERY_PRESENT = "present"
	CONST_ENCAP_DOT1Q = "dot1q"
	CONST_ENCAP_ISL = "isl"
	CONST_ENCAP_NEGOTIATE = "negotiate"
	CONST_ENCAP_PROPRIETARY = "proprietary"
	CONST_ENCAP_UNKNOWN = "unknown"
	CONST_IF_ROLE_DIAG = "diag"
	CONST_IF_ROLE_FCOE_NAS_STORAGE = "fcoe-nas-storage"
	CONST_IF_ROLE_FCOE_STORAGE = "fcoe-storage"
	CONST_IF_ROLE_FCOE_UPLINK = "fcoe-uplink"
	CONST_IF_ROLE_MGMT = "mgmt"
	CONST_IF_ROLE_MONITOR = "monitor"
	CONST_IF_ROLE_NAS_STORAGE = "nas-storage"
	CONST_IF_ROLE_NETWORK = "network"
	CONST_IF_ROLE_NETWORK_FCOE_UPLINK = "network-fcoe-uplink"
	CONST_IF_ROLE_SERVER = "server"
	CONST_IF_ROLE_SERVICE = "service"
	CONST_IF_ROLE_STORAGE = "storage"
	CONST_IF_ROLE_UNKNOWN = "unknown"
	CONST_IF_TYPE_AGGREGATION = "aggregation"
	CONST_IF_TYPE_PHYSICAL = "physical"
	CONST_IF_TYPE_UNKNOWN = "unknown"
	CONST_IF_TYPE_VIRTUAL = "virtual"
	CONST_MODE_E = "E"
	CONST_MODE_F = "F"
	CONST_MODE_SD = "SD"
	CONST_MODE_ACCESS = "access"
	CONST_MODE_FABRIC = "fabric"
	CONST_MODE_N_PROXY = "n_proxy"
	CONST_MODE_TRUNK = "trunk"
	CONST_MODE_UNKNOWN = "unknown"
	CONST_NEW_FE_TS_NEVER = "never"
	CONST_OPER_STATE_ADMIN_DOWN = "admin-down"
	CONST_OPER_STATE_ERROR_DISABLED = "error-disabled"
	CONST_OPER_STATE_FAILED = "failed"
	CONST_OPER_STATE_HARDWARE_FAILURE = "hardware-failure"
	CONST_OPER_STATE_INDETERMINATE = "indeterminate"
	CONST_OPER_STATE_LINK_DOWN = "link-down"
	CONST_OPER_STATE_LINK_UP = "link-up"
	CONST_OPER_STATE_NO_LICENSE = "no-license"
	CONST_OPER_STATE_SFP_NOT_PRESENT = "sfp-not-present"
	CONST_OPER_STATE_SOFTWARE_FAILURE = "software-failure"
	CONST_OPER_STATE_UDLD_AGGR_DOWN = "udld-aggr-down"
	CONST_OPER_STATE_UP = "up"
	CONST_PEER_CHASSIS_ID_N_A = "N/A"
	CONST_SWITCH_ID_A = "A"
	CONST_SWITCH_ID_B = "B"
	CONST_SWITCH_ID_NONE = "NONE"
	CONST_XCVR_TYPE_10GBASEER = "10gbaseer"
	CONST_XCVR_TYPE_10GBASELR = "10gbaselr"
	CONST_XCVR_TYPE_10GBASELRM = "10gbaselrm"
	CONST_XCVR_TYPE_10GBASESR = "10gbasesr"
	CONST_XCVR_TYPE_CWDM1471 = "cwdm1471"
	CONST_XCVR_TYPE_CWDM1531 = "cwdm1531"
	CONST_XCVR_TYPE_CWDM1551 = "cwdm1551"
	CONST_XCVR_TYPE_FET = "fet"
	CONST_XCVR_TYPE_H10GCU1M = "h10gcu1m"
	CONST_XCVR_TYPE_H10GCU3M = "h10gcu3m"
	CONST_XCVR_TYPE_H10GCU5M = "h10gcu5m"
	CONST_XCVR_TYPE_H10GCU7M = "h10gcu7m"
	CONST_XCVR_TYPE_H10GLRMSM = "h10glrmsm"
	CONST_XCVR_TYPE_H10GUSR = "h10gusr"
	CONST_XCVR_TYPE_SFP = "sfp"
	CONST_XCVR_TYPE_UNKNOWN = "unknown"
	CONST_XCVR_TYPE_X2 = "x2"
