import sys, os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from UcsBase import ManagedObject
sys.path.remove(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

class FabricFcoeSanEp(ManagedObject):
	def __init__(self):
		ManagedObject.__init__(self,"FabricFcoeSanEp")

	@staticmethod
	def ClassId():
		return "fabricFcoeSanEp"

	ADMIN_STATE = "AdminState"
	CHASSIS_ID = "ChassisId"
	CONFIG_STATE = "ConfigState"
	DN = "Dn"
	EP_DN = "EpDn"
	ETH_LINK_PROFILE_NAME = "EthLinkProfileName"
	FCOE_STATE = "FcoeState"
	FCOE_STATE_REASON = "FcoeStateReason"
	IF_ROLE = "IfRole"
	IF_TYPE = "IfType"
	LIC_GP = "LicGP"
	LIC_STATE = "LicState"
	LOCALE = "Locale"
	NAME = "Name"
	OPER_ETH_LINK_PROFILE_NAME = "OperEthLinkProfileName"
	OPER_STATE = "OperState"
	OPER_STATE_REASON = "OperStateReason"
	PEER_CHASSIS_ID = "PeerChassisId"
	PEER_DN = "PeerDn"
	PEER_PORT_ID = "PeerPortId"
	PEER_SLOT_ID = "PeerSlotId"
	PORT_ID = "PortId"
	RN = "Rn"
	SLOT_ID = "SlotId"
	STATUS = "Status"
	SWITCH_ID = "SwitchId"
	TRANSPORT = "Transport"
	TYPE = "Type"
	UDLD_OPER_STATE = "UdldOperState"
	USR_LBL = "UsrLbl"
	WARNINGS = "Warnings"

	CONST_ADMIN_STATE_DISABLED = "disabled"
	CONST_ADMIN_STATE_ENABLED = "enabled"
	CONST_CHASSIS_ID_N_A = "N/A"
	CONST_CONFIG_STATE_APPLIED = "applied"
	CONST_CONFIG_STATE_INCONSISTENT = "inconsistent"
	CONST_FCOE_STATE_ADMIN_DOWN = "admin-down"
	CONST_FCOE_STATE_ERROR_DISABLED = "error-disabled"
	CONST_FCOE_STATE_FAILED = "failed"
	CONST_FCOE_STATE_HARDWARE_FAILURE = "hardware-failure"
	CONST_FCOE_STATE_INDETERMINATE = "indeterminate"
	CONST_FCOE_STATE_LINK_DOWN = "link-down"
	CONST_FCOE_STATE_LINK_UP = "link-up"
	CONST_FCOE_STATE_NO_LICENSE = "no-license"
	CONST_FCOE_STATE_SFP_NOT_PRESENT = "sfp-not-present"
	CONST_FCOE_STATE_SOFTWARE_FAILURE = "software-failure"
	CONST_FCOE_STATE_UDLD_AGGR_DOWN = "udld-aggr-down"
	CONST_FCOE_STATE_UP = "up"
	CONST_IF_ROLE_DIAG = "diag"
	CONST_IF_ROLE_FCOE_NAS_STORAGE = "fcoe-nas-storage"
	CONST_IF_ROLE_FCOE_STORAGE = "fcoe-storage"
	CONST_IF_ROLE_FCOE_UPLINK = "fcoe-uplink"
	CONST_IF_ROLE_MGMT = "mgmt"
	CONST_IF_ROLE_MONITOR = "monitor"
	CONST_IF_ROLE_NAS_STORAGE = "nas-storage"
	CONST_IF_ROLE_NETWORK = "network"
	CONST_IF_ROLE_NETWORK_FCOE_UPLINK = "network-fcoe-uplink"
	CONST_IF_ROLE_SERVER = "server"
	CONST_IF_ROLE_SERVICE = "service"
	CONST_IF_ROLE_STORAGE = "storage"
	CONST_IF_ROLE_UNKNOWN = "unknown"
	CONST_IF_TYPE_AGGREGATION = "aggregation"
	CONST_IF_TYPE_PHYSICAL = "physical"
	CONST_IF_TYPE_UNKNOWN = "unknown"
	CONST_IF_TYPE_VIRTUAL = "virtual"
	CONST_LIC_STATE_LICENSE_EXPIRED = "license-expired"
	CONST_LIC_STATE_LICENSE_GRACEPERIOD = "license-graceperiod"
	CONST_LIC_STATE_LICENSE_INSUFFICIENT = "license-insufficient"
	CONST_LIC_STATE_LICENSE_OK = "license-ok"
	CONST_LIC_STATE_NOT_APPLICABLE = "not-applicable"
	CONST_LIC_STATE_UNKNOWN = "unknown"
	CONST_OPER_STATE_DOWN = "down"
	CONST_OPER_STATE_ERROR_MISCONFIGURED = "error-misconfigured"
	CONST_OPER_STATE_UNKNOWN = "unknown"
	CONST_OPER_STATE_UP = "up"
	CONST_PEER_CHASSIS_ID_N_A = "N/A"
	CONST_SWITCH_ID_A = "A"
	CONST_SWITCH_ID_B = "B"
	CONST_SWITCH_ID_NONE = "NONE"
	CONST_UDLD_OPER_STATE_ADMIN_DISABLED = "admin-disabled"
	CONST_UDLD_OPER_STATE_BIDIRECTIONAL = "bidirectional"
	CONST_UDLD_OPER_STATE_ECHO_EMPTY = "echo-empty"
	CONST_UDLD_OPER_STATE_MISMATCH = "mismatch"
	CONST_UDLD_OPER_STATE_TX_RX_LOOP = "tx-rx-loop"
	CONST_UDLD_OPER_STATE_UNIDIRECTIONAL = "unidirectional"
	CONST_UDLD_OPER_STATE_UNKNOWN = "unknown"
