import sys, os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from UcsBase import ManagedObject
sys.path.remove(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

class FabricPathEp(ManagedObject):
	def __init__(self):
		ManagedObject.__init__(self,"FabricPathEp")

	@staticmethod
	def ClassId():
		return "fabricPathEp"

	C_TYPE = "CType"
	CHASSIS_ID = "ChassisId"
	DIAG_LLDP_TRANSMIT = "DiagLldpTransmit"
	DN = "Dn"
	EP_DN = "EpDn"
	IF_ROLE = "IfRole"
	IF_TYPE = "IfType"
	LOCALE = "Locale"
	NAME = "Name"
	PEER_CHASSIS_ID = "PeerChassisId"
	PEER_DN = "PeerDn"
	PEER_MAC = "PeerMac"
	PEER_PORT_ID = "PeerPortId"
	PEER_SLOT_ID = "PeerSlotId"
	PORT_ID = "PortId"
	RN = "Rn"
	SIDE = "Side"
	SLOT_ID = "SlotId"
	STATUS = "Status"
	SWITCH_ID = "SwitchId"
	TRANSPORT = "Transport"
	TYPE = "Type"

	CONST_C_TYPE_MUX = "mux"
	CONST_C_TYPE_MUX_ACCESS = "mux-access"
	CONST_C_TYPE_MUX_FABRIC = "mux-fabric"
	CONST_C_TYPE_MUX_FABRICPC = "mux-fabricpc"
	CONST_C_TYPE_MUX_FABRICPC_TO_HOSTPC = "mux-fabricpc-to-hostpc"
	CONST_C_TYPE_MUX_FABRICPC_TO_HOSTPORT = "mux-fabricpc-to-hostport"
	CONST_C_TYPE_MUX_FABRICPORT_TO_HOSTPC = "mux-fabricport-to-hostpc"
	CONST_C_TYPE_MUX_HOSTPC_TO_ADAPTORPC = "mux-hostpc-to-adaptorpc"
	CONST_C_TYPE_MUX_TO_CHASSIS = "mux-to-chassis"
	CONST_C_TYPE_MUX_TO_HOST = "mux-to-host"
	CONST_C_TYPE_SWITCH_ACCESS = "switch-access"
	CONST_C_TYPE_SWITCH_FABRIC = "switch-fabric"
	CONST_C_TYPE_SWITCH_FABRICPC = "switch-fabricpc"
	CONST_C_TYPE_SWITCH_TO_HOST = "switch-to-host"
	CONST_C_TYPE_SWITCH_TO_MUX = "switch-to-mux"
	CONST_CHASSIS_ID_N_A = "N/A"
	CONST_DIAG_LLDP_TRANSMIT_FALSE = "false"
	CONST_DIAG_LLDP_TRANSMIT_NO = "no"
	CONST_DIAG_LLDP_TRANSMIT_TRUE = "true"
	CONST_DIAG_LLDP_TRANSMIT_YES = "yes"
	CONST_IF_ROLE_DIAG = "diag"
	CONST_IF_ROLE_FCOE_NAS_STORAGE = "fcoe-nas-storage"
	CONST_IF_ROLE_FCOE_STORAGE = "fcoe-storage"
	CONST_IF_ROLE_FCOE_UPLINK = "fcoe-uplink"
	CONST_IF_ROLE_MGMT = "mgmt"
	CONST_IF_ROLE_MONITOR = "monitor"
	CONST_IF_ROLE_NAS_STORAGE = "nas-storage"
	CONST_IF_ROLE_NETWORK = "network"
	CONST_IF_ROLE_NETWORK_FCOE_UPLINK = "network-fcoe-uplink"
	CONST_IF_ROLE_SERVER = "server"
	CONST_IF_ROLE_SERVICE = "service"
	CONST_IF_ROLE_STORAGE = "storage"
	CONST_IF_ROLE_UNKNOWN = "unknown"
	CONST_IF_TYPE_AGGREGATION = "aggregation"
	CONST_IF_TYPE_PHYSICAL = "physical"
	CONST_IF_TYPE_UNKNOWN = "unknown"
	CONST_IF_TYPE_VIRTUAL = "virtual"
	CONST_PEER_CHASSIS_ID_N_A = "N/A"
	CONST_SIDE_LEFT = "left"
	CONST_SIDE_RIGHT = "right"
	CONST_SWITCH_ID_A = "A"
	CONST_SWITCH_ID_B = "B"
	CONST_SWITCH_ID_NONE = "NONE"
