import sys, os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from UcsHandle import UcsVersion, UcsPropertyMeta, UcsMoMeta
from UcsMeta import _VersionMeta
sys.path.remove(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

PROPERTY_DICT = {
	"ChildAction":UcsPropertyMeta("ChildAction", "childAction", "string", _VersionMeta.Version221b, UcsPropertyMeta.Internal, 0x1L, None, None, """((deleteAll|ignore|deleteNonPresent),){0,2}(deleteAll|ignore|deleteNonPresent){0,1}""", [], ["0-4294967295"]),
	"ConfigWarnings":UcsPropertyMeta("ConfigWarnings", "configWarnings", "string", _VersionMeta.Version222c, UcsPropertyMeta.ReadOnly, None, None, None, """((defaultValue|not-applicable|kvm-mgmt-policy-unsupported),){0,2}(defaultValue|not-applicable|kvm-mgmt-policy-unsupported){0,1}""", [], ["0-4294967295"]),
	"Dn":UcsPropertyMeta("Dn", "dn", "string", _VersionMeta.Version221b, UcsPropertyMeta.ReadOnly, 0x2L, 0, 256, None, [], ["0-4294967295"]),
	"IscsiConfigIssues":UcsPropertyMeta("IscsiConfigIssues", "iscsiConfigIssues", "string", _VersionMeta.Version221b, UcsPropertyMeta.ReadOnly, None, None, None, """((defaultValue|not-applicable|static-target-mix|native-vlan|auto-target-auth|iscsi-config|missing-vlan|invalid-target-name|initiator-name|ip-addr-dhcp|init-target-passwd|auto-target-init|iscsi-initiator-ip-address|iqn-pool-name|vnic-name|no-luns|unclassified|init-identity|target-name|no-vlan-ip|invalid-mac|iscsi-cardinality|allowed-vlan|internal-cfg-error|auth-profile-same),){0,24}(defaultValue|not-applicable|static-target-mix|native-vlan|auto-target-auth|iscsi-config|missing-vlan|invalid-target-name|initiator-name|ip-addr-dhcp|init-target-passwd|auto-target-init|iscsi-initiator-ip-address|iqn-pool-name|vnic-name|no-luns|unclassified|init-identity|target-name|no-vlan-ip|invalid-mac|iscsi-cardinality|allowed-vlan|internal-cfg-error|auth-profile-same){0,1}""", [], ["0-4294967295"]),
	"NetworkConfigIssues":UcsPropertyMeta("NetworkConfigIssues", "networkConfigIssues", "string", _VersionMeta.Version221b, UcsPropertyMeta.ReadOnly, None, None, None, """((defaultValue|not-applicable|network-feature-capability-mismatch|switch-virtual-if-capacity|conflicting-vlan-access|named-vlan-inaccessible|unsupported-multicast-policy|permit-unresolved|vlan-port-capacity|pinning-invalid),){0,9}(defaultValue|not-applicable|network-feature-capability-mismatch|switch-virtual-if-capacity|conflicting-vlan-access|named-vlan-inaccessible|unsupported-multicast-policy|permit-unresolved|vlan-port-capacity|pinning-invalid){0,1}""", [], ["0-4294967295"]),
	"Rn":UcsPropertyMeta("Rn", "rn", "string", _VersionMeta.Version221b, UcsPropertyMeta.ReadOnly, 0x4L, 0, 256, None, [], ["0-4294967295"]),
	"ServerConfigIssues":UcsPropertyMeta("ServerConfigIssues", "serverConfigIssues", "string", _VersionMeta.Version221b, UcsPropertyMeta.ReadOnly, None, None, None, """((defaultValue|not-applicable|insufficient-power-budget|server-position-requirement|boot-configuration-unsupported|compute-undiscovered|power-group-requirement|imgsec-policy-invalid|soft-pinning-vlan-mismatch|missing-firmware-image|resource-ownership-conflict|boot-order-pxe|vmedia-policy-unsupported|insufficient-resources|mac-address-assignment|remote-service-profile|server-feature-capability-mismatch|incompat-bios-for-sriov-vnics|processor-requirement|provsrv-policy-invalid|board-controller-update-unsupported|non-interrupt-fsm-running|boot-order-san-image-path|bootip-policy-invalid|boot-policy-vmedia-invalid|memory-requirement|system-uuid-assignment|domain-requirement|boot-configuration-invalid|incompatible-bios-image|remote-policy|qos-policy-invalid|compute-unavailable|physical-requirement|hostimg-policy-invalid|vmedia-mount-config-invalid|migration|wwnn-derivation-from-vhba|duplicate-address-conflict|boot-order-iscsi),){0,39}(defaultValue|not-applicable|insufficient-power-budget|server-position-requirement|boot-configuration-unsupported|compute-undiscovered|power-group-requirement|imgsec-policy-invalid|soft-pinning-vlan-mismatch|missing-firmware-image|resource-ownership-conflict|boot-order-pxe|vmedia-policy-unsupported|insufficient-resources|mac-address-assignment|remote-service-profile|server-feature-capability-mismatch|incompat-bios-for-sriov-vnics|processor-requirement|provsrv-policy-invalid|board-controller-update-unsupported|non-interrupt-fsm-running|boot-order-san-image-path|bootip-policy-invalid|boot-policy-vmedia-invalid|memory-requirement|system-uuid-assignment|domain-requirement|boot-configuration-invalid|incompatible-bios-image|remote-policy|qos-policy-invalid|compute-unavailable|physical-requirement|hostimg-policy-invalid|vmedia-mount-config-invalid|migration|wwnn-derivation-from-vhba|duplicate-address-conflict|boot-order-iscsi){0,1}""", [], ["0-4294967295"]),
	"Status":UcsPropertyMeta("Status", "status", "string", _VersionMeta.Version221b, UcsPropertyMeta.ReadWrite, 0x8L, None, None, """((removed|created|modified|deleted),){0,3}(removed|created|modified|deleted){0,1}""", [], ["0-4294967295"]),
	"StorageConfigIssues":UcsPropertyMeta("StorageConfigIssues", "storageConfigIssues", "string", _VersionMeta.Version221b, UcsPropertyMeta.ReadOnly, None, None, None, """((defaultValue|not-applicable|flexflash-metadata|zone-capacity|missing-raid-key|destructive-local-disk-config|storage-feature-capability-mismatch|flexflash-controller|incompatible-disk-types|storage-path-configuration-error|incompatible-number-of-local-disks|flexflash-card|wwnn-assignment|incompatible-raid-level),){0,13}(defaultValue|not-applicable|flexflash-metadata|zone-capacity|missing-raid-key|destructive-local-disk-config|storage-feature-capability-mismatch|flexflash-controller|incompatible-disk-types|storage-path-configuration-error|incompatible-number-of-local-disks|flexflash-card|wwnn-assignment|incompatible-raid-level){0,1}""", [], ["0-4294967295"]),
	"VnicConfigIssues":UcsPropertyMeta("VnicConfigIssues", "vnicConfigIssues", "string", _VersionMeta.Version221b, UcsPropertyMeta.ReadOnly, None, None, None, """((defaultValue|not-applicable|adaptor-protected-eth-capability|vif-resources-overprovisioned|ungrouped-domain|unresolved-remote-vlan-name|invalid-wwn|service-profile-virtualization-conflict|fcoe-capacity|wwpn-derivation-virtualized-port|unresolved-vlan-name|vnic-virtualization-netflow-conflict|pinning-vlan-mismatch|adaptor-requirement|vnic-not-ha-ready|missing-ipv4-inband-mgmt-addr|unresolved-remote-vsan-name|mac-derivation-virtualized-port|vnic-virtualization-conflict|vnic-vlan-assignment-error|insufficient-vhba-capacity|inaccessible-vlan|unable-to-update-ucsm|soft-pinning-vlan-mismatch|connection-placement|vnic-vcon-provisioning-change|missing-ipv6-inband-mgmt-addr|missing-primary-vlan|adaptor-fcoe-capability|vfc-vnic-pvlan-conflict|virtualization-not-supported|unresolved-vsan-name|insufficient-vnic-capacity|unassociated-vlan|dynamic-vf-vnic|wwpn-assignment|missing-ipv4-addr|pinned-target-misconfig),){0,37}(defaultValue|not-applicable|adaptor-protected-eth-capability|vif-resources-overprovisioned|ungrouped-domain|unresolved-remote-vlan-name|invalid-wwn|service-profile-virtualization-conflict|fcoe-capacity|wwpn-derivation-virtualized-port|unresolved-vlan-name|vnic-virtualization-netflow-conflict|pinning-vlan-mismatch|adaptor-requirement|vnic-not-ha-ready|missing-ipv4-inband-mgmt-addr|unresolved-remote-vsan-name|mac-derivation-virtualized-port|vnic-virtualization-conflict|vnic-vlan-assignment-error|insufficient-vhba-capacity|inaccessible-vlan|unable-to-update-ucsm|soft-pinning-vlan-mismatch|connection-placement|vnic-vcon-provisioning-change|missing-ipv6-inband-mgmt-addr|missing-primary-vlan|adaptor-fcoe-capability|vfc-vnic-pvlan-conflict|virtualization-not-supported|unresolved-vsan-name|insufficient-vnic-capacity|unassociated-vlan|dynamic-vf-vnic|wwpn-assignment|missing-ipv4-addr|pinned-target-misconfig){0,1}""", [], ["0-4294967295"]),
	"Meta":UcsMoMeta("LsIssues", "lsIssues", "config-issue", _VersionMeta.Version221b, "InputOutput", 0xfL, [], [u'faultInst'], [None], ["admin", "ls-compute", "ls-config", "ls-server"])
}

