import sys, os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from UcsBase import ManagedObject
sys.path.remove(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

class LsmaintAck(ManagedObject):
	def __init__(self):
		ManagedObject.__init__(self,"LsmaintAck")

	@staticmethod
	def ClassId():
		return "lsmaintAck"

	ACKED = "Acked"
	ACKED_BY = "AckedBy"
	ADMIN_STATE = "AdminState"
	AUTO_DELETE = "AutoDelete"
	CHANGE_BY = "ChangeBy"
	CHANGE_DETAILS = "ChangeDetails"
	CHANGE_MODE = "ChangeMode"
	CHANGES = "Changes"
	CONFIG_ISSUES = "ConfigIssues"
	DEPLOYMENT_MODE = "DeploymentMode"
	DESCR = "Descr"
	DISR = "Disr"
	DN = "Dn"
	IGNORE_CAP = "IgnoreCap"
	MODIFIED = "Modified"
	NAME = "Name"
	OLD_PN_DN = "OldPnDn"
	OPER_SCHEDULER = "OperScheduler"
	OPER_STATE = "OperState"
	POLICY_LEVEL = "PolicyLevel"
	POLICY_OWNER = "PolicyOwner"
	PREV_OPER_STATE = "PrevOperState"
	RN = "Rn"
	SCHEDULER = "Scheduler"
	STATUS = "Status"

	CONST_ADMIN_STATE_TRIGGER = "trigger"
	CONST_ADMIN_STATE_TRIGGER_IMMEDIATE = "trigger-immediate"
	CONST_ADMIN_STATE_TRIGGERED = "triggered"
	CONST_ADMIN_STATE_UNTRIGGERED = "untriggered"
	CONST_ADMIN_STATE_USER_ACK = "user-ack"
	CONST_ADMIN_STATE_USER_DISCARD = "user-discard"
	CONST_AUTO_DELETE_FALSE = "false"
	CONST_AUTO_DELETE_NO = "no"
	CONST_AUTO_DELETE_TRUE = "true"
	CONST_AUTO_DELETE_YES = "yes"
	CONST_CHANGE_MODE_CONFIG = "config"
	CONST_CHANGE_MODE_DIAG = "diag"
	CONST_CHANGE_MODE_DIAG_CONFIG = "diag-config"
	CONST_CHANGE_MODE_DIAG_UNCONFIG = "diag-unconfig"
	CONST_CHANGE_MODE_FORCE_UNCONFIG = "force-unconfig"
	CONST_CHANGE_MODE_NO_CHANGE = "no-change"
	CONST_CHANGE_MODE_REDISCOVER = "rediscover"
	CONST_CHANGE_MODE_REMOVE_CONFIG = "remove-config"
	CONST_CHANGE_MODE_UNCONFIG = "unconfig"
	CONST_DEPLOYMENT_MODE_IMMEDIATE = "immediate"
	CONST_DEPLOYMENT_MODE_TIMER_AUTOMATIC = "timer-automatic"
	CONST_DEPLOYMENT_MODE_USER_ACK = "user-ack"
	CONST_IGNORE_CAP_FALSE = "false"
	CONST_IGNORE_CAP_NO = "no"
	CONST_IGNORE_CAP_TRUE = "true"
	CONST_IGNORE_CAP_YES = "yes"
	CONST_INT_ID_NONE = "none"
	CONST_OPER_STATE_ACTIVE = "active"
	CONST_OPER_STATE_APPLIED = "applied"
	CONST_OPER_STATE_APPLY_PENDING = "apply-pending"
	CONST_OPER_STATE_EVALUATED = "evaluated"
	CONST_OPER_STATE_EVALUATION_PENDING = "evaluation-pending"
	CONST_OPER_STATE_EXPIRED = "expired"
	CONST_OPER_STATE_NONE = "none"
	CONST_OPER_STATE_PENDING = "pending"
	CONST_OPER_STATE_UNTRIGGERED = "untriggered"
	CONST_OPER_STATE_WAITING_FOR_DEPENDENCY = "waiting-for-dependency"
	CONST_OPER_STATE_WAITING_FOR_MAINT_WINDOW = "waiting-for-maint-window"
	CONST_OPER_STATE_WAITING_FOR_USER = "waiting-for-user"
	CONST_POLICY_OWNER_LOCAL = "local"
	CONST_POLICY_OWNER_PENDING_POLICY = "pending-policy"
	CONST_POLICY_OWNER_POLICY = "policy"
	CONST_PREV_OPER_STATE_ACTIVE = "active"
	CONST_PREV_OPER_STATE_APPLIED = "applied"
	CONST_PREV_OPER_STATE_APPLY_PENDING = "apply-pending"
	CONST_PREV_OPER_STATE_EVALUATED = "evaluated"
	CONST_PREV_OPER_STATE_EVALUATION_PENDING = "evaluation-pending"
	CONST_PREV_OPER_STATE_EXPIRED = "expired"
	CONST_PREV_OPER_STATE_NONE = "none"
	CONST_PREV_OPER_STATE_PENDING = "pending"
	CONST_PREV_OPER_STATE_UNTRIGGERED = "untriggered"
	CONST_PREV_OPER_STATE_WAITING_FOR_DEPENDENCY = "waiting-for-dependency"
	CONST_PREV_OPER_STATE_WAITING_FOR_MAINT_WINDOW = "waiting-for-maint-window"
	CONST_PREV_OPER_STATE_WAITING_FOR_USER = "waiting-for-user"
