import sys, os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from UcsBase import ManagedObject
sys.path.remove(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

class ProcessorErrorStats(ManagedObject):
	def __init__(self):
		ManagedObject.__init__(self,"ProcessorErrorStats")

	@staticmethod
	def ClassId():
		return "processorErrorStats"

	DN = "Dn"
	INTERVALS = "Intervals"
	MIRRORING_INTER_SOCK_ERRORS = "MirroringInterSockErrors"
	MIRRORING_INTER_SOCK_ERRORS15_MIN = "MirroringInterSockErrors15Min"
	MIRRORING_INTER_SOCK_ERRORS15_MIN_H = "MirroringInterSockErrors15MinH"
	MIRRORING_INTER_SOCK_ERRORS1_DAY = "MirroringInterSockErrors1Day"
	MIRRORING_INTER_SOCK_ERRORS1_DAY_H = "MirroringInterSockErrors1DayH"
	MIRRORING_INTER_SOCK_ERRORS1_HOUR = "MirroringInterSockErrors1Hour"
	MIRRORING_INTER_SOCK_ERRORS1_HOUR_H = "MirroringInterSockErrors1HourH"
	MIRRORING_INTER_SOCK_ERRORS1_WEEK = "MirroringInterSockErrors1Week"
	MIRRORING_INTER_SOCK_ERRORS1_WEEK_H = "MirroringInterSockErrors1WeekH"
	MIRRORING_INTER_SOCK_ERRORS2_WEEKS = "MirroringInterSockErrors2Weeks"
	MIRRORING_INTER_SOCK_ERRORS2_WEEKS_H = "MirroringInterSockErrors2WeeksH"
	MIRRORING_INTRA_SOCK_ERRORS = "MirroringIntraSockErrors"
	MIRRORING_INTRA_SOCK_ERRORS15_MIN = "MirroringIntraSockErrors15Min"
	MIRRORING_INTRA_SOCK_ERRORS15_MIN_H = "MirroringIntraSockErrors15MinH"
	MIRRORING_INTRA_SOCK_ERRORS1_DAY = "MirroringIntraSockErrors1Day"
	MIRRORING_INTRA_SOCK_ERRORS1_DAY_H = "MirroringIntraSockErrors1DayH"
	MIRRORING_INTRA_SOCK_ERRORS1_HOUR = "MirroringIntraSockErrors1Hour"
	MIRRORING_INTRA_SOCK_ERRORS1_HOUR_H = "MirroringIntraSockErrors1HourH"
	MIRRORING_INTRA_SOCK_ERRORS1_WEEK = "MirroringIntraSockErrors1Week"
	MIRRORING_INTRA_SOCK_ERRORS1_WEEK_H = "MirroringIntraSockErrors1WeekH"
	MIRRORING_INTRA_SOCK_ERRORS2_WEEKS = "MirroringIntraSockErrors2Weeks"
	MIRRORING_INTRA_SOCK_ERRORS2_WEEKS_H = "MirroringIntraSockErrors2WeeksH"
	RN = "Rn"
	SMI_LINK_CORR_ERRORS = "SmiLinkCorrErrors"
	SMI_LINK_CORR_ERRORS15_MIN = "SmiLinkCorrErrors15Min"
	SMI_LINK_CORR_ERRORS15_MIN_H = "SmiLinkCorrErrors15MinH"
	SMI_LINK_CORR_ERRORS1_DAY = "SmiLinkCorrErrors1Day"
	SMI_LINK_CORR_ERRORS1_DAY_H = "SmiLinkCorrErrors1DayH"
	SMI_LINK_CORR_ERRORS1_HOUR = "SmiLinkCorrErrors1Hour"
	SMI_LINK_CORR_ERRORS1_HOUR_H = "SmiLinkCorrErrors1HourH"
	SMI_LINK_CORR_ERRORS1_WEEK = "SmiLinkCorrErrors1Week"
	SMI_LINK_CORR_ERRORS1_WEEK_H = "SmiLinkCorrErrors1WeekH"
	SMI_LINK_CORR_ERRORS2_WEEKS = "SmiLinkCorrErrors2Weeks"
	SMI_LINK_CORR_ERRORS2_WEEKS_H = "SmiLinkCorrErrors2WeeksH"
	SMI_LINK_UNCORR_ERRORS = "SmiLinkUncorrErrors"
	SMI_LINK_UNCORR_ERRORS15_MIN = "SmiLinkUncorrErrors15Min"
	SMI_LINK_UNCORR_ERRORS15_MIN_H = "SmiLinkUncorrErrors15MinH"
	SMI_LINK_UNCORR_ERRORS1_DAY = "SmiLinkUncorrErrors1Day"
	SMI_LINK_UNCORR_ERRORS1_DAY_H = "SmiLinkUncorrErrors1DayH"
	SMI_LINK_UNCORR_ERRORS1_HOUR = "SmiLinkUncorrErrors1Hour"
	SMI_LINK_UNCORR_ERRORS1_HOUR_H = "SmiLinkUncorrErrors1HourH"
	SMI_LINK_UNCORR_ERRORS1_WEEK = "SmiLinkUncorrErrors1Week"
	SMI_LINK_UNCORR_ERRORS1_WEEK_H = "SmiLinkUncorrErrors1WeekH"
	SMI_LINK_UNCORR_ERRORS2_WEEKS = "SmiLinkUncorrErrors2Weeks"
	SMI_LINK_UNCORR_ERRORS2_WEEKS_H = "SmiLinkUncorrErrors2WeeksH"
	SPARING_ERRORS = "SparingErrors"
	SPARING_ERRORS15_MIN = "SparingErrors15Min"
	SPARING_ERRORS15_MIN_H = "SparingErrors15MinH"
	SPARING_ERRORS1_DAY = "SparingErrors1Day"
	SPARING_ERRORS1_DAY_H = "SparingErrors1DayH"
	SPARING_ERRORS1_HOUR = "SparingErrors1Hour"
	SPARING_ERRORS1_HOUR_H = "SparingErrors1HourH"
	SPARING_ERRORS1_WEEK = "SparingErrors1Week"
	SPARING_ERRORS1_WEEK_H = "SparingErrors1WeekH"
	SPARING_ERRORS2_WEEKS = "SparingErrors2Weeks"
	SPARING_ERRORS2_WEEKS_H = "SparingErrors2WeeksH"
	STATUS = "Status"
	SUSPECT = "Suspect"
	THRESHOLDED = "Thresholded"
	TIME_COLLECTED = "TimeCollected"
	UPDATE = "Update"

	CONST_SUSPECT_FALSE = "false"
	CONST_SUSPECT_NO = "no"
	CONST_SUSPECT_TRUE = "true"
	CONST_SUSPECT_YES = "yes"
