import sys, os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from UcsBase import ManagedObject
sys.path.remove(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

class StorageLocalDisk(ManagedObject):
	def __init__(self):
		ManagedObject.__init__(self,"StorageLocalDisk")

	@staticmethod
	def ClassId():
		return "storageLocalDisk"

	BLOCK_SIZE = "BlockSize"
	CONNECTION_PROTOCOL = "ConnectionProtocol"
	DEVICE_TYPE = "DeviceType"
	DISK_STATE = "DiskState"
	DN = "Dn"
	ID = "Id"
	LC = "Lc"
	LINK_SPEED = "LinkSpeed"
	MODEL = "Model"
	NUMBER_OF_BLOCKS = "NumberOfBlocks"
	OPER_QUALIFIER_REASON = "OperQualifierReason"
	OPERABILITY = "Operability"
	POWER_STATE = "PowerState"
	PRESENCE = "Presence"
	REVISION = "Revision"
	RN = "Rn"
	SERIAL = "Serial"
	SIZE = "Size"
	STATUS = "Status"
	VENDOR = "Vendor"

	CONST_BLOCK_SIZE_UNKNOWN = "unknown"
	CONST_CONNECTION_PROTOCOL_SAS = "SAS"
	CONST_CONNECTION_PROTOCOL_SATA = "SATA"
	CONST_CONNECTION_PROTOCOL_UNSPECIFIED = "unspecified"
	CONST_DEVICE_TYPE_HDD = "HDD"
	CONST_DEVICE_TYPE_SSD = "SSD"
	CONST_DEVICE_TYPE_UNSPECIFIED = "unspecified"
	CONST_DISK_STATE_COPYBACK = "copyback"
	CONST_DISK_STATE_DEDICATED_HOT_SPARE = "dedicated-hot-spare"
	CONST_DISK_STATE_DISABLED_FOR_REMOVAL = "disabled-for-removal"
	CONST_DISK_STATE_FAILED = "failed"
	CONST_DISK_STATE_FOREIGN_CONFIGURATION = "foreign-configuration"
	CONST_DISK_STATE_GLOBAL_HOT_SPARE = "global-hot-spare"
	CONST_DISK_STATE_JBOD = "jbod"
	CONST_DISK_STATE_OFFLINE = "offline"
	CONST_DISK_STATE_ONLINE = "online"
	CONST_DISK_STATE_PREDICTIVE_FAILURE = "predictive-failure"
	CONST_DISK_STATE_REBUILDING = "rebuilding"
	CONST_DISK_STATE_UNCONFIGURED_BAD = "unconfigured-bad"
	CONST_DISK_STATE_UNCONFIGURED_GOOD = "unconfigured-good"
	CONST_DISK_STATE_UNKNOWN = "unknown"
	CONST_LC_ALLOCATED = "allocated"
	CONST_LC_AVAILABLE = "available"
	CONST_LC_DEALLOCATED = "deallocated"
	CONST_LC_REPURPOSED = "repurposed"
	CONST_LINK_SPEED_1_5_GBPS = "1-5-gbps"
	CONST_LINK_SPEED_12_GBPS = "12-gbps"
	CONST_LINK_SPEED_3_GBPS = "3-gbps"
	CONST_LINK_SPEED_6_GBPS = "6-gbps"
	CONST_LINK_SPEED_UNKNOWN = "unknown"
	CONST_NUMBER_OF_BLOCKS_UNKNOWN = "unknown"
	CONST_OPERABILITY_ACCESSIBILITY_PROBLEM = "accessibility-problem"
	CONST_OPERABILITY_AUTO_UPGRADE = "auto-upgrade"
	CONST_OPERABILITY_BIOS_POST_TIMEOUT = "bios-post-timeout"
	CONST_OPERABILITY_CHASSIS_LIMIT_EXCEEDED = "chassis-limit-exceeded"
	CONST_OPERABILITY_CONFIG = "config"
	CONST_OPERABILITY_DECOMISSIONING = "decomissioning"
	CONST_OPERABILITY_DEGRADED = "degraded"
	CONST_OPERABILITY_DISABLED = "disabled"
	CONST_OPERABILITY_DISCOVERY = "discovery"
	CONST_OPERABILITY_DISCOVERY_FAILED = "discovery-failed"
	CONST_OPERABILITY_EQUIPMENT_PROBLEM = "equipment-problem"
	CONST_OPERABILITY_FABRIC_CONN_PROBLEM = "fabric-conn-problem"
	CONST_OPERABILITY_FABRIC_UNSUPPORTED_CONN = "fabric-unsupported-conn"
	CONST_OPERABILITY_IDENTIFY = "identify"
	CONST_OPERABILITY_IDENTITY_UNESTABLISHABLE = "identity-unestablishable"
	CONST_OPERABILITY_INOPERABLE = "inoperable"
	CONST_OPERABILITY_LINK_ACTIVATE_BLOCKED = "link-activate-blocked"
	CONST_OPERABILITY_MALFORMED_FRU = "malformed-fru"
	CONST_OPERABILITY_NOT_SUPPORTED = "not-supported"
	CONST_OPERABILITY_OPERABLE = "operable"
	CONST_OPERABILITY_PEER_COMM_PROBLEM = "peer-comm-problem"
	CONST_OPERABILITY_PERFORMANCE_PROBLEM = "performance-problem"
	CONST_OPERABILITY_POST_FAILURE = "post-failure"
	CONST_OPERABILITY_POWER_PROBLEM = "power-problem"
	CONST_OPERABILITY_POWERED_OFF = "powered-off"
	CONST_OPERABILITY_REMOVED = "removed"
	CONST_OPERABILITY_THERMAL_PROBLEM = "thermal-problem"
	CONST_OPERABILITY_UNKNOWN = "unknown"
	CONST_OPERABILITY_UPGRADE_PROBLEM = "upgrade-problem"
	CONST_OPERABILITY_VOLTAGE_PROBLEM = "voltage-problem"
	CONST_POWER_STATE_ACTIVE = "active"
	CONST_POWER_STATE_POWERSAVE = "powersave"
	CONST_POWER_STATE_TRANSITIONING = "transitioning"
	CONST_POWER_STATE_UNKNOWN = "unknown"
	CONST_PRESENCE_EMPTY = "empty"
	CONST_PRESENCE_EQUIPPED = "equipped"
	CONST_PRESENCE_EQUIPPED_IDENTITY_UNESTABLISHABLE = "equipped-identity-unestablishable"
	CONST_PRESENCE_EQUIPPED_NOT_PRIMARY = "equipped-not-primary"
	CONST_PRESENCE_EQUIPPED_SLAVE = "equipped-slave"
	CONST_PRESENCE_EQUIPPED_WITH_MALFORMED_FRU = "equipped-with-malformed-fru"
	CONST_PRESENCE_INACCESSIBLE = "inaccessible"
	CONST_PRESENCE_MISMATCH = "mismatch"
	CONST_PRESENCE_MISMATCH_IDENTITY_UNESTABLISHABLE = "mismatch-identity-unestablishable"
	CONST_PRESENCE_MISMATCH_SLAVE = "mismatch-slave"
	CONST_PRESENCE_MISSING = "missing"
	CONST_PRESENCE_MISSING_SLAVE = "missing-slave"
	CONST_PRESENCE_NOT_SUPPORTED = "not-supported"
	CONST_PRESENCE_UNAUTHORIZED = "unauthorized"
	CONST_PRESENCE_UNKNOWN = "unknown"
	CONST_SIZE_UNKNOWN = "unknown"
