import sys, os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from UcsBase import ManagedObject
sys.path.remove(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

class SwEthLanEp(ManagedObject):
	def __init__(self):
		ManagedObject.__init__(self,"SwEthLanEp")

	@staticmethod
	def ClassId():
		return "swEthLanEp"

	ADMIN_SPEED = "AdminSpeed"
	ADMIN_STATE = "AdminState"
	CHASSIS_ID = "ChassisId"
	DN = "Dn"
	EP_DN = "EpDn"
	IF_ROLE = "IfRole"
	IF_TYPE = "IfType"
	LC = "Lc"
	LOCALE = "Locale"
	NAME = "Name"
	PC_ID = "PcId"
	PEER_CHASSIS_ID = "PeerChassisId"
	PEER_DN = "PeerDn"
	PEER_PORT_ID = "PeerPortId"
	PEER_SLOT_ID = "PeerSlotId"
	PORT_ID = "PortId"
	PRIORITY_FLOW_CTRL = "PriorityFlowCtrl"
	RECV_FLOW_CTRL = "RecvFlowCtrl"
	RN = "Rn"
	SEND_FLOW_CTRL = "SendFlowCtrl"
	SLOT_ID = "SlotId"
	STATUS = "Status"
	SWITCH_ID = "SwitchId"
	TRANSPORT = "Transport"
	TYPE = "Type"
	UDLD_ADMIN_STATE = "UdldAdminState"
	UDLD_MODE = "UdldMode"

	CONST_ADMIN_SPEED_10GBPS = "10gbps"
	CONST_ADMIN_SPEED_1GBPS = "1gbps"
	CONST_ADMIN_SPEED_20GBPS = "20gbps"
	CONST_ADMIN_SPEED_40GBPS = "40gbps"
	CONST_ADMIN_SPEED_INDETERMINATE = "indeterminate"
	CONST_ADMIN_STATE_DISABLED = "disabled"
	CONST_ADMIN_STATE_ENABLED = "enabled"
	CONST_CHASSIS_ID_N_A = "N/A"
	CONST_IF_ROLE_DIAG = "diag"
	CONST_IF_ROLE_FCOE_NAS_STORAGE = "fcoe-nas-storage"
	CONST_IF_ROLE_FCOE_STORAGE = "fcoe-storage"
	CONST_IF_ROLE_FCOE_UPLINK = "fcoe-uplink"
	CONST_IF_ROLE_MGMT = "mgmt"
	CONST_IF_ROLE_MONITOR = "monitor"
	CONST_IF_ROLE_NAS_STORAGE = "nas-storage"
	CONST_IF_ROLE_NETWORK = "network"
	CONST_IF_ROLE_NETWORK_FCOE_UPLINK = "network-fcoe-uplink"
	CONST_IF_ROLE_SERVER = "server"
	CONST_IF_ROLE_SERVICE = "service"
	CONST_IF_ROLE_STORAGE = "storage"
	CONST_IF_ROLE_UNKNOWN = "unknown"
	CONST_IF_TYPE_AGGREGATION = "aggregation"
	CONST_IF_TYPE_PHYSICAL = "physical"
	CONST_IF_TYPE_UNKNOWN = "unknown"
	CONST_IF_TYPE_VIRTUAL = "virtual"
	CONST_LC_ALLOCATED = "allocated"
	CONST_LC_AVAILABLE = "available"
	CONST_LC_DEALLOCATED = "deallocated"
	CONST_LC_PENDING = "pending"
	CONST_LC_REPURPOSED = "repurposed"
	CONST_PEER_CHASSIS_ID_N_A = "N/A"
	CONST_PRIORITY_FLOW_CTRL_AUTO = "auto"
	CONST_PRIORITY_FLOW_CTRL_ON = "on"
	CONST_RECV_FLOW_CTRL_OFF = "off"
	CONST_RECV_FLOW_CTRL_ON = "on"
	CONST_SEND_FLOW_CTRL_OFF = "off"
	CONST_SEND_FLOW_CTRL_ON = "on"
	CONST_SWITCH_ID_A = "A"
	CONST_SWITCH_ID_B = "B"
	CONST_SWITCH_ID_NONE = "NONE"
	CONST_UDLD_ADMIN_STATE_DISABLED = "disabled"
	CONST_UDLD_ADMIN_STATE_ENABLED = "enabled"
	CONST_UDLD_MODE_AGGRESSIVE = "aggressive"
	CONST_UDLD_MODE_NORMAL = "normal"
